# Generated by Django 6.0.5 on 2026-05-29 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('proposal', models.FileField(upload_to='proposals/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('WINNING', 'Winning'), ('LOSING', 'Losing')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='procurement.procurement')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='accounts.vendorprofile')),
            ],
            options={
                'unique_together': {('procurement', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='BidOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_events', to='bids.bid')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
