# Generated by Django 6.0.5 on 2026-05-29 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deadline', models.DateTimeField(help_text='When bidding closes')),
                ('reveal_date', models.DateTimeField(help_text='When bid contents become visible (blind until then)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for bidding'), ('CLOSED', 'Bidding closed'), ('AWARDED', 'Contract awarded'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('awarded_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vendorprofile')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='procurement.procurement')),
            ],
        ),
    ]
